/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...catchAll]': RouteRecordInfo<
      '/[...catchAll]',
      '/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/bookings': RouteRecordInfo<
      '/admin/bookings',
      '/admin/bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/login': RouteRecordInfo<
      '/admin/login',
      '/admin/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/members': RouteRecordInfo<
      '/admin/members',
      '/admin/members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/register': RouteRecordInfo<
      '/admin/register',
      '/admin/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/booking': RouteRecordInfo<
      '/booking',
      '/booking',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...catchAll].vue': {
      routes:
        | '/[...catchAll]'
      views:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'src/pages/admin/bookings.vue': {
      routes:
        | '/admin/bookings'
      views:
        | never
    }
    'src/pages/admin/login.vue': {
      routes:
        | '/admin/login'
      views:
        | never
    }
    'src/pages/admin/members.vue': {
      routes:
        | '/admin/members'
      views:
        | never
    }
    'src/pages/admin/register.vue': {
      routes:
        | '/admin/register'
      views:
        | never
    }
    'src/pages/booking.vue': {
      routes:
        | '/booking'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
